// <auto-generated />
using FinalTest413.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinalTest413.Migrations
{
    [DbContext(typeof(QuoteDbContext))]
    partial class QuoteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.24");

            modelBuilder.Entity("FinalTest413.Models.Quote", b =>
                {
                    b.Property<int>("QuoteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Citation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuoteText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .HasColumnType("TEXT");

                    b.HasKey("QuoteID");

                    b.ToTable("Quotes");

                    b.HasData(
                        new
                        {
                            QuoteID = 1,
                            Author = "Virgil",
                            Citation = "",
                            Date = "19 B.C.",
                            QuoteText = "Fortune Favors the Bold.",
                            Subject = ""
                        },
                        new
                        {
                            QuoteID = 2,
                            Author = "Mahatma Gandhi",
                            Citation = "",
                            Date = "1913",
                            QuoteText = "You must be the change you wish to see in the world.",
                            Subject = ""
                        },
                        new
                        {
                            QuoteID = 3,
                            Author = "René Descartes",
                            Citation = "",
                            Date = "1637",
                            QuoteText = "I think, therefore I am.",
                            Subject = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
